Airflow test
tsandil/the_movies_db pull request #8
Opened 2024-09-19 14:55 UTC by tsandil

This PR will create Airflow Orchestration along with some features. This PR will also solve this [issue](https://github.com/tsandil/the_movies_db/issues/7)

2024-09-19 15:01 UTC, Sunnyinho requested changes
Implement the comments

2024-09-19 15:01 UTC, Sunnyinho commented on .astro/dag_integrity_exceptions.txt
EOL

2024-09-19 15:01 UTC, Sunnyinho commented on dags/flows/test.py
Implement this in `themoviedb.py` file

2024-09-19 15:01 UTC, Sunnyinho commented on utilities/queries.py
Add when matched condition

2024-09-21 17:52 UTC, tsandil commented on utilities/queries.py
When matched cases applied.

2024-09-30 10:36 UTC, Sunnyinho approved these changes
push this inside the hole

2024-09-30 10:36 UTC, Sunnyinho commented on .astro/config.yaml
> +
Only add one line remove extra lines

2024-09-30 10:37 UTC, merged